variables:
  GIT_SUBMODULE_STRATEGY: recursive

deploy:
  stage: deploy
  environment: production
  only:
    - master
  tags:
    - ksar
  script:
    - hugo
    - rsync public/ ${PROJECT_PATH} --recursive --ignore-times --checksum --delete --exclude=.git*
