## Basic Configuration

baseurl = "https://kubakh.name/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Svyatoslav Kubakh"
title = "Svyatoslav Kubakh"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Svyatoslav Kubakh"
intro = "Web developer"
description = ""
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Svyatoslav Kubakh home page"
keywords = "homepage,blog,hugo,developer"

## Social Accounts
[params.social]
github = "svyatoslav-kubakh"
instagram = "realksar"
linkedin = "svyatoslav-kubakh"
#twitter = "realksar"
facebook = "svyatoslav.kubakh"
#google = "SvyatoslavKubakh"
#stackoverflow = "<username>"
#email = "svyatoslav.kubakh@gmail.com"

## Extras
[params.extra]
copyright = "© 2018. Svyatoslav Kubakh. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
#hightlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
